#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo ""
echo -e "           \033[1;33m● \033[1;32m PREPARANDO O VPS \033[1;33m●\033[0m"
fun_preparando () {
    apt-get update -y > /dev/null 2>&1 
	apt-get install figlet -y > /dev/null 2>&1
}
fun_bar 'fun_preparando'
clear
echo ""
#
rm /root/siteupdate > /dev/null 2>&1
mkdir bkp
cd /var/www/html/pages/system/
cp pass.php /root/bkp/
cd
echo -ne "\033[1;33m●\033[1;32m DESEJA CONTINUAR\033[1;31m\033[1;32m\033[1;33m? \033[1;33m● \033[1;31m[s/n]: ";read resp
echo ""
clear
if [[ "$resp" = @(s|S) ]]; then
cd /var/www/html/ 
rm -rf admin index.php sair.php app-assets lib assets src logando.php pages favicon.ico home.php login.php validacao.php > /dev/null 2>&1
cd
rm /root/site.zip > /dev/null 2>&1
rm $HOME/site.zip > /dev/null 2>&1
IP=$(wget -qO- ipv4.icanhazip.com)
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
rm $HOME/siteupdate > /dev/null 2>&1
#
clear
echo -e "\E[44;1;37m    ATUALIZAR O PAINEL     \E[0m"
echo ""
echo -e "                                \033[1;31mBy @Universe_say\033[1;36m"
echo -e "   Painel Web" | figlet 
echo -e "                               \033[1;31mPainelSSH site\033[1;36m"
echo ""
echo -e "\n\033[1;36m  INICIANDO ATUALIZACAO PODE DEMORAR\033[1;33m"
cd /var/www/html/
fun_atualizando () {
    wget https://www.dropbox.com/s/i4b0c30mjj2004h/site.zip > /dev/null 2>&1
sleep 1
unzip site.zip > /dev/null 2>&1
rm -rf site.zip index.html > /dev/null 2>&1
service apache2 restart
}
fun_bar 'fun_atualizando'
sleep 1
cd
rm /var/www/html/pages/system/pass.php
cd /root/bkp
cp pass.php /var/www/html/pages/system/
cd
rm -r bkp
# 
echo -e "\n\033[1;36m  FINALIZANDO ATUALIZACAO\033[1;33m"
fun_finalizando () {
service apache2 restart
clear
/etc/init.d/cron reload > /dev/null 2>&1
/etc/init.d/cron restart > /dev/null 2>&1
cd /bin
chmod 777 /var/www/html/admin/pages/download
service apache2 restart
service apache2 restart
}
fun_bar 'fun_finalizando'
clear
IP=$(wget -qO- ipv4.icanhazip.com)
clear
echo -e "\E[44;1;37m    ATUALIZACAO FINALIZADA \E[0m"
echo -e "   PainelSSH " | figlet
echo -e "      site" | figlet
echo -e "                 \033[1;31mBy @Universe_say\033[1;36m"
echo ""
sed -i "s;upload_max_filesize = 2M;upload_max_filesize = 20M;g" /etc/php5/apache2/php.ini > /dev/null 2>&1
service apache2 restart
fi
cat /dev/null > ~/.bash_history && history -c
rm /root/siteupdate > /dev/null 2>&1
rm /root/updateweb.sh > /dev/null 2>&1
rm /root/site.zip > /dev/null 2>&1
menu